version: '3.0'

services:
  grafana:
    container_name: 'mapgl-community'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - $PWD/dist:/var/lib/grafana/plugins/mapgl-panel
      - $PWD/provisioning:/etc/grafana/provisioning
      - $PWD/.seed:/usr/share/grafana/public/seed
      - $PWD/.seed/public_svg:/usr/share/grafana/public/img/icons/mapgl
      - $PWD/docker_data/grafana_data:/var/lib/grafana
      - $PWD/docker_data/certs:/certs

    env_file:
      - $PWD/docker_data/grafana_conf/graf.env

    restart: always
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource, marcusolsson-static-datasource
      - GF_FEATURE_TOGGLES_ENABLE=enableDatagridEditing, editPanelCSVDragAndDrop
      - GF_PLUGIN_ALLOW_LOCAL_MODE=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - HTTP_USER="{{ GRAFANA_USER }}"
      - HTTP_PASS="{{ GRAFANA_PASSWD }}"

  # nginx:
  #   container_name: 'mapgl-community-nginx'
  #   build: ./nginx
  #   restart: always
  #   environment:
  #     - GRAFANA_HOST=172.17.0.1
  #   ports:
  #     - 80:80/tcp
  #   depends_on:
  #     - grafana

